FROM nishchalatattve/hp:user

RUN mkdir -p /home/nishchalatattve/.vscode-server/data/Machine 
COPY settings.json /home/nishchalatattve/.vscode-server/data/Machine/settings.json

RUN mkdir -p /home/nishchalatattve/latex_workspace 
WORKDIR /home/nishchalatattve/latex_workspace